---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  namespace: ip-app
  labels:
    app: ip-app
    name: redis-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app
      name: redis-db
  serviceName: redis
  template:
    metadata:
      name: redis-db
      labels:
        app: ip-app
        name: redis-db
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        command: ['redis-server', '--appendonly', 'yes']
        volumeMounts:
          - name: redis-volume
            mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 30
        ports:
        - containerPort: 6379
      restartPolicy: Always