---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  namespace: ip-app
  labels:
    app: ip-app
    name: redis-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/redis
