---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ip-app
  labels:
    app: ip-app
    name: redis-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ip-app
    name: redis-db
