---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  namespace: ip-app
  labels:
    app: ip-app
    name: flask-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app
      name: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: ip-app
        name: flask-app
    spec:
      containers:
      - name: flask-app
        image: kxpic/ip-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 5000
        readinessProbe: 
          httpGet: 
            path: /get-ip
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /get-ip
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 1
      restartPolicy: OnFailure