---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: ip-app
  labels:
    app: ip-app
    name: flask-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: ip-app
    name: flask-app